# Generated by Django 4.2.16 on 2024-09-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='display_name',
        ),
    ]
