# Generated by Django 5.0.6 on 2024-09-15 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=100)),
                ('body', models.TextField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
