# Generated by Django 4.2.16 on 2024-09-23 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0013_alter_comment_options_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Reply',
        ),
    ]
