# Generated by Django 4.2.16 on 2024-09-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_rename_author_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parent_post',
            new_name='parent_comment',
        ),
    ]
