# Generated by Django 4.2.16 on 2024-09-26 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0017_likedcomments_comment_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedComments',
            new_name='LikedComment',
        ),
    ]
